### PR TITLE
add if program

### PR DESCRIPTION
**Pull request by smitapawar0195**

### CODE REVIEW

**Review by shrikantkatkur — COMMENTED** [review]
instaed of scanner class,enter input directly

**Comment by smitapawar0195** [comment]
please review my 2 pr

**Review by shrikantkatkur — APPROVED** [review]
approved

**Review by shrikantkatkur — APPROVED** [review]
instaed of scanner class,enter input directly

**Comment by shrikantkatkur** [comment]
merged into master

**Pull request merged**
